"""added dynamic restaurant working hours

Revision ID: 490d4685668c
Revises: 868c16d3e1b9
Create Date: 2026-05-11 19:28:24.274114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '490d4685668c'
down_revision: Union[str, Sequence[str], None] = '868c16d3e1b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('restaurants', sa.Column('opens_at', sa.Time(), nullable=True))
    op.add_column('restaurants', sa.Column('closes_at', sa.Time(), nullable=True))
    op.add_column('restaurants', sa.Column('is_24_7', sa.Boolean(), server_default=sa.false(), nullable=False))
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('reviews', 'author_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.drop_constraint(op.f('reviews_user_id_fkey'), 'reviews', type_='foreignkey')
    op.create_foreign_key(None, 'reviews', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.create_foreign_key(op.f('reviews_user_id_fkey'), 'reviews', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('reviews', 'author_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('reviews', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('restaurants', 'is_24_7')
    op.drop_column('restaurants', 'closes_at')
    op.drop_column('restaurants', 'opens_at')
    # ### end Alembic commands ###
